name: NeuroLibre - Add publication to the website 
on:
  repository_dispatch:
    types: [publish]
env:
  PUB_NAME: ${{ github.event.client_payload.pub_name }}
  PUB_INFO: ${{ toJson(github.event.client_payload.pub_info) }}
  PUB_LABEL: ${{ toJson(github.event.client_payload.pub_info.submission.category) }}
  PUB_TAG: ${{ github.event.client_payload.pub_tag }}
jobs:
  updateWebsite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout neurolibre/neurolibre.com
        uses: actions/checkout@v2
      - name: Dump the JSON received from dispatch 
        run: |
          mkdir -p data/nlbooks
          echo "$PUB_INFO" > data/nlbooks/${{env.PUB_NAME}}.json
          echo ::set-env name=PUB_AUTHOR::$(if [ -z "${{ github.event.client_payload.pub_info.authors[1].name }}" ]; then echo ${{ github.event.client_payload.pub_info.authors[0].name }}; else echo ${{ github.event.client_payload.pub_info.authors[0].name }} et al.; fi)
          echo ::set-env name=TAG_TYPE::$(echo $PUB_TAG | awk -F"-" '{print $1}')
          echo ::set-env name=TAG_VER::$(echo $PUB_TAG | awk -F"-" '{print $2}')
      - name: Conditionally assign ENV vars
        run: |          
          if [[ ${{ env.TAG_TYPE }} == "pub" ]] && [[ ${{ env.TAG_VER }} == "v1" ]]; then
            echo "First version."
            echo ::set-env name=PR_TITLE::$(echo "🆕✨ ${{ env.PUB_NAME }} by  ${{ env.PUB_AUTHOR }}")
            echo ::set-env name=PR_LABELS::$(echo "new, ${{ env.PUB_LABEL }}")
          elif [[ ${{ env.TAG_TYPE }} == "pub" ]] && [[ ${{ env.TAG_VER }} != "v1" ]]; then
            echo "New version."
            echo ::set-env name=PR_TITLE::$(echo "🆙🚀 ${{ env.PUB_NAME }} (${{ env.TAG_VER }}) by  ${{ env.PUB_AUTHOR }}")
            echo ::set-env name=PR_LABELS::$(echo "update, ${{ env.PUB_LABEL }}")
          else
            echo "This is NOT type publish. Ensure that workflow logic is in harmony with trigger tags."
          fi
          echo ::set-env name=IMG_LINK::$(echo "https://github.com/roboneurotest/${{ env.PUB_NAME }}/blob/master/${{ env.PUB_NAME }}_featured.png?raw=true")
          echo ::set-env name=VER_LINK::$(echo "https://github.com/roboneurotest/${{ env.PUB_NAME }}/releases/tag/${{ env.TAG_TYPE }}-${{ env.TAG_VER }}")
          echo ::set-env name=STATUS_BADGE::$(echo "https://github.com/roboneurotest/${{ env.PUB_NAME }}/workflows/Publish%20to%20neurolibre.com/badge.svg?branch=${{ env.TAG_TYPE }}-${{ env.TAG_VER }}")
          echo ::set-env name=STATUS_LINK::$(echo "https://github.com/roboneurotest/${{ env.PUB_NAME }}/actions")
          echo ::set-env name=BOOK_BADGE::$(echo "https://img.shields.io/badge/NeuroLibreBook-${{ env.PUB_NAME }}-red.svg?&style=flat&color=ff0000")
          echo ::set-env name=INF_MSG::$(echo "🤖 This pull request has been automatially created from [${{ env.PUB_NAME }}](https://github.com/roboneurotest/${{ env.PUB_NAME }}) repository.")
   
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.PAT }}
          commit-message: '[ADD] ${{ env.PUB_NAME }}.json'
          committer: NeuroLibre <neurolibre@gmail.com>
          author: NeuroLibre < NeuroLibre@users.noreply.github.com>
          title: '${{ env.PR_TITLE }}'
          body: |
            <p align="center" ><img src="${{ env.IMG_LINK }}" alt="featured" width="300"><p align="center">
            <hr>
            
            ### ${{ github.event.client_payload.pub_info.title }}
            
            #### ${{ env.INF_MSG }}            
            
            ## 🛫 Checklist 
            
            [![Version badge](https://img.shields.io/badge/${{ env.TAG_TYPE }}-${{ env.TAG_VER }}-green)](${{ env.VER_LINK }}) [![Status badge](${{ env.STATUS_BADGE }})](${{ env.STATUS_LINK }}) [![Book](${{ env.BOOK_BADGE }})](https://neurolibre.com)
            
            - [ ] **Build is passing**
              It may take some time status badge to fetch status (green|pass or red|fail). Click the badge to monitor the process in real time.
            <br>

            - [ ] **Publication is properly versioned**
               Click the badge to see the associated release in the source repository. Publication tags respect `pub-v*` format, where suffix is always `v1` for the first version. 
            <br>

            - [ ] **Publication is live**
               It may take publication for a while to go live after a successful build due to page build and domain resolution. Note that the publication pages are built from the `gh-pages` branch of the source repository. 
            <br>

            - [ ] **[Publication metadata](https://github.com/neurolibre/roboneurotest/blob/master/data/nlbooks/${{ env.PUB_NAME }}.json) is OK.**
            <br>

            - [ ] **Badges are properly populated on the publication card and the links are not broken.** 
            <br>

            - [ ] **Featured image is visible on the publication card.**
            <br>
            
            TODO: 
            * Mention (@) first author
            * Use GitHub teams for reviewers & assigness
            * Note about checking `gh-pages` settings 
            * Update link/repo agahkarakuzu --> neurolibre
            
            <hr>
            <p align="center"><img src="https://www.neurolibre.com/img/neurolibre_logo.svg" alt="featured" width="50"/><br>NeuroLibre</p>
            
          labels: '${{ env.PR_LABELS }}'
          assignees: agahkarakuzu
          reviewers: agahkarakuzu
          branch: '${{ env.PUB_NAME }}'
